[package]
name = "bytewren-proto"
description = "Zero-copy network protocol parsers"
keywords = ["networking", "packet", "parser"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true